### ISSUE TITLE
"Tiny lazy annotated stream library" official example: Issues compiling the code and running it

### ISSUE THREAD

**Issue by Muzietto** [mattbierner/khepri#124]
I am unable to compile as-is the stream library example provided in the overview of the language. I am using compiler version 1.2.4

There are also issues about running its code after small modifications that allow compilation.

Sample code to be found at https://github.com/Muzietto/khepri-lambda

# COMPILING ISSUE
I am trying to compile the following files:
- https://github.com/Muzietto/khepri-lambda/blob/master/first_tests/stream_test/original_source/using_stream.kep
- https://github.com/Muzietto/khepri-lambda/blob/master/first_tests/stream_test/original_source/lib/stream.kep

with the command (given in the stream_test directory):

`
khepri original_source -o build
`

Error message is: `'original_source\using_stream.kep' At {line:4 col:34} expected object pattern element`

The culprit appears to be the attempt to import `(+<)`.

In order to compile the source, line 4 has to be changed so to import `cons` instead of `(+<)`.

The compiling code is to be found in directory: https://github.com/Muzietto/khepri-lambda/tree/master/first_tests/stream_test/source

# RUNNING ISSUE
After compiling the code I am still unable to get the pipelining example right. This is possibly my own mistake when using `cons` instead of `(+<)`, but my attempts always end up with a `NaN` produced by the `foldl` run.

My latest attempt is:

      cons (1, s 
          |> reverse)
          |> foldl@((/), 120)
          |> console.log;

and is contained in:
- https://github.com/Muzietto/khepri-lambda/blob/master/first_tests/stream_test/source/using_stream.kep

In order to run my stream library code: download the GitHub project, have a localhost webserver pointing at the filesystem and load the file:
- first_tests/requirejs_stream_test.html

My project contains experiments with both AMD and NPM package styles. The issues I am mentioning are independent of the package management style used.

It would be highly beneficial if a fully compilable and running version of the stream library (with its using_stream.kep file) were downloadable from the khepri-lang.org site, rather than have only samples of arguably not-compilable code in the wiki.

Thank you for your attention.

**Comment by mattbierner** [comment]
Thanks for reporting the issue, it is fixed now. Here's the output AMD:

```
define(["require", "exports", "stream"], (function(require, exports, stream) {
    "use strict";
    var __plus_lt = stream["+<"],
        foldl = stream["foldl"],
        reverse = stream["reverse"],
        __div = (function(x, y) {
            return (x / y);
        }),
        s = stream.from([2, 3, 4]);
    console.log(foldl(__div, 120, reverse(__plus_lt(1, s))));
}));
```

The example is basically a really stripped down version on [Nu](http://mattbierner.github.io/nu/). Although the example code will work, you may also want to check out the real source: https://github.com/mattbierner/nu/blob/master/lib/stream.kep
