### ISSUE TITLE
Apparently unable to use |>> operator

### ISSUE THREAD

**Issue by marco-faustinelli** [mattbierner/khepri#129]
I am trying to use operator `|>>` inside a function.

Please see line 25 of:

https://github.com/Muzietto/geiesidioms/blob/master/kep/kep-source/lib/khepri-idioms.kep

Compiler returns: `undeclared symbol |>>`.

What is the case here?

**Comment by marco-faustinelli** [comment]
I managed to use `<<|`

https://github.com/Muzietto/geiesidioms/blob/master/kep/kep-source/lib/khepri-idioms.kep#L24

But still `|>>` should be available.

**Comment by mattbierner** [comment]
Fixed. Had `||>` defined in the builtins instead of `|>>`
